### ISSUE TITLE
Add a feature/scenario output format

### ISSUE THREAD

**Issue by mirogta** [go-bdd/gobdd#116]
**Is your feature request related to a problem? Please describe.**

We find the output from godog which shows/repeats the features and scenarios in the build output very nice. I've tried to convince people to use gobdd instead but they miss this feature.

**Describe the solution you'd like**

We'd like to have an option to show the godog-like output with the features and scenarios. See e.g. Example Step 2 in https://github.com/cucumber/godog

**Describe alternatives you've considered**

N/A

**Additional context**
![image](https://user-images.githubusercontent.com/5633108/86022672-98986500-ba22-11ea-9587-f12ad13db569.png)

**Comment by bkielbasa** [comment]
it's a more complicated thing. Godog has it's own binary to be able to have full control over the output of the test execution. When running it using `go test` we have to use the built-in `t.Log()` etc.

I have some ideas about how to resolve it but it requires deeper research and designing. The idea is to generate a report file that can be interpreted to present things like this or upload it to a SaaS that would present it as well as compare with other test execution. But for now, it's not possible to output it like this one. I'll create a proposal with it shortly.

If you have any ideas about how we can do it - let me know.

**Comment by bkielbasa** [comment]
Here's the proposal: https://github.com/go-bdd/gobdd/issues/122
If you have any other idea - comment it or create your own proposal :)

**Comment by mirogta** [comment]
Awesome - I'm missing a Superthumb emoji here :-)
