### ISSUE TITLE
Add before/after step callbacks

### ISSUE THREAD

**Issue by jirikuncar** [go-bdd/gobdd#118]
**Is your feature request related to a problem? Please describe.**
I have a repetitive set up and teardown code for many step functions.

**Describe the solution you'd like**
- `gobdd.WithBeforeStep(func(ctx gobdd.Context))`
- `gobdd.WithAfterStep(func(ctx gobdd.Context))`

**Describe alternatives you've considered**
Adding a "decorator" to my step functions.

**Additional context**
It would be nice if the default context contains current feature and scenario references.

**Comment by sagikazarmark** [comment]
Having information about tags might make sense, but I don't think it's a good practice to write hooks and branch off based on feature names.

I'd much rather check if a certain value is available in a context (eg. db store) and run tear down logic based on that fact.

Can you share a bit more about your use case?

**Comment by bkielbasa** [comment]
I agree with @sagikazarmark. It looks you want to attach some logic based on tags.

> What are Cucumber Tags?
Let’s say you have got many different feature files that cover all the different functionality of the application. Now there can be a certain situation in the project where you like to execute just a SmokeTests or End2EndTests or may be RegressionTests. One approach is that you start creating new feature files with the name of the type like SmokeTests.features or End2EndTests.feature and copy-paste your existing tests in the same. But this would make the project filthy and would require more maintenance in future. So how to manage execution in such cases?

> For this, Cucumber has already provided a way to organize your scenario execution by using tags in feature file. We can define each scenario with a useful tag. Later, in the runner file, we can decide which specific tag (and so as the scenario(s)) we want Cucumber to execute. Tag starts with “@”. After “@” you can have any relevant text to define your tag like @SmokeTests just above the scenarios you like to mark. Then to target these tagged scenarios just specify the tags names in the CucumberOptions as tags = {“@SmokeTests”}.

ref: https://www.toolsqa.com/cucumber/cucumber-tags/

So tags should be used to exclude/include some test to execute but should not have the impact on the logic inside of the step/scenario etc

**Comment by bkielbasa** [comment]
If you think we misunderstood your issue, reopen the issue. For now, I'm closing it.

**Comment by jirikuncar** [comment]
I would like to include the tags in traces so it is still valid.

> I have a repetitive set up and teardown code for many step functions.

IMHO this is still valid to allow for before/after step hooks.

**Comment by jirikuncar** [comment]
There is a related issue #121 which would be nice to solve together.

**Comment by bkielbasa** [comment]
hmm, I think there's no reason for not doing it. Questions are:
* do we need the context there?
* do we want to add additional information into the context?
* should the context be extended to contain the new data or create a new "thing" and add it as the second parameter in the callback?

**Comment by jirikuncar** [comment]
> do we need the context there?

definitely yes!

> do we want to add additional information into the context?

it might not be necessary if the hook gets the information as separate arguments and then it might be the responsibility of the user to extend the context.

> should the context be extended to contain the new data or create a new "thing" and add it as the second parameter in the callback?

It might be better to provide the information as separate hook argument. I really like the way `pytest-bdd` is doing it for their hooks.
