### ISSUE TITLE
Add current test, scenario and step to Context

### ISSUE THREAD

**Issue by jirikuncar** [go-bdd/gobdd#121]
**Is your feature request related to a problem? Please describe.**
1. I am using VCR library to record requests from client library to server and I would like to use correct cassette name depending from which scenario/step the request has been made.
2. I would like to create tracing span for each step and have them grouped by scenario.

**Describe the solution you'd like**
Add information about current test, scenario and step to context.

https://github.com/go-bdd/gobdd/blob/master/gobdd.go#L307

**Describe alternatives you've considered**
`-`

**Additional context**
See https://pytest-bdd.readthedocs.io/en/latest/#hooks

**Comment by bkielbasa** [comment]
Hi! Is the feature still needed?

**Comment by jirikuncar** [comment]
Yes. There is still no way to access the scenario or step from test hooks.
