### ISSUE TITLE
Get status of suite

### ISSUE THREAD

**Issue by tylerauerbeck** [go-bdd/gobdd#125]
Occasionally there are times when I only want to do something after tests have completed successfully. Is this information stored anywhere that I can get at programmatically?

**Comment by bkielbasa** [comment]
Hi, thanks for your question!
Could you tell me know how do you imagine it to look like?

**Comment by bkielbasa** [comment]
If you want to do something depending on some criteria, you can put it into the context
```go
func check(t gobdd.StepTest, ctx gobdd.Context, sum int) {
	if sum != received {
                ctx.Set("failed, true)
		t.Error(errors.New("the math does not work for you"))
	}
}
```

and check this value wherever you want. Closing for now but if you have any troubles with using it, don't hesitate to reopen the issue.

**Comment by tylerauerbeck** [comment]
Thanks @bkielbasa . I think that is good when you need to match certain criteria. I just needed something a bit more `did one of these features fail`, so I was able to get around it by checking `t.Failed()` after `suite.Run()` has completed. Works for our use case, but may have some sharp edges for others.

**Comment by bkielbasa** [comment]
Could you ahow how you imagine it to work in a semi real code?
