### ISSUE TITLE
NewSuite undefined when trying to run your example code.

### ISSUE THREAD

**Issue by EmmanuelSammy** [go-bdd/gobdd#134]
**Describe the bug**
NewSuite is undefined when trying to use your example in the readme.md

**To Reproduce**
- did a go get to get go-bdd
- created bdd_test.go file and added package and pasted readme.md example
- ran go test ./...
- get ./bdd_test.go:28:11: undefined: NewSuite

**Expected behavior**
- expected there to be no errors in the code and test to run

**Additional context**
code where the error is:
func TestScenarios(t *testing.T) {
	suite := NewSuite(t) <--- error here
	suite.AddStep(`I add (\d+) and (\d+)`, add)
	suite.AddStep(`I the result should equal (\d+)`, check)
	suite.Run()
}

**Comment by EmmanuelSammy** [comment]
Never mind used gobdd.NewSuite() and it works thanks and sorry for the inconvenience.

**Comment by bkielbasa** [comment]
thanks for your issue. I updated the readme file and put the missing `gobdd.NewSuite` there. Hopefully, it won't confuse anyone else :)
