### ISSUE TITLE
When a step is not defined display an example step to implement

### ISSUE THREAD

**Issue by bkielbasa** [go-bdd/gobdd#15]
How godog does it :)

![image](https://user-images.githubusercontent.com/1235620/59423291-25e62880-8dd2-11e9-9d76-b9b3d416def6.png)

**Comment by bkielbasa** [comment]
I added the `needs investigation` label because I'm seeking for other ways of solving the problem.
This is just one of solutions.

**Comment by mirogta** [comment]
For inspiration:
https://specflow.org/documentation/Generating-Skeleton-Code/

I've used it extensively while on a .NET project... and it's really slick. You can choose to generate a skeleton code or copy content to clipboard for any missing step definitions.

I would envisage that perhaps some flags to the go-bdd runtime could generate the code (i.e. `.go` files) or perhaps even copy the code to clipboard - using https://github.com/atotto/clipboard ? I understand that adding such dependency might be undesirable. But on the other hand, wouldn't this cover the typical scenario? I mean what would you do with the output in the console - wouldn't you copy it to clipboard and paste to a file? At least I do that with godog. So why not skip that step and put it in the clipboard automatically :-)

I assume that an alternative like pipe the stdout output to a file won't be a typical scenario.

**Comment by bkielbasa** [comment]
thanks for the link!

I'm not sure if everyone would like such automatization. That's an interference in the user's system.

**Comment by bkielbasa** [comment]
maybe as an additional library?

**Comment by mirogta** [comment]
> maybe as an additional library?

Maybe a VSCode add-on for go-bdd?

**Comment by bkielbasa** [comment]
Integrations with IDEs are in my plans :) but first of all, we have to have stable API and release the very first stable version of the lib.

**Comment by mirogta** [comment]
Awesome. Happy to contribute, have quite decent experience with TypeScript and always wanted to dive deeper into VSCode extensions development... originally for godog, but this looks like a much nicer project :-)

**Comment by bkielbasa** [comment]
Nice to hear that :) I'll back to it when we'll release v1.0 :)

**Comment by bkielbasa** [comment]
@mirogta We're coming closer to the stable version. Are you still interested in building the extension? If yes, I can create a new project in the go-bdd project for the extension and set you as a contributor.

**Comment by mirogta** [comment]
Definitely! I'm following go-bbd updates quite closely :)

**Comment by bkielbasa** [comment]
closing because we're waiting for a proposal or IDE-specific solution.
