### ISSUE TITLE
Catching invalid step functions

### ISSUE THREAD

**Issue by sagikazarmark** [go-bdd/gobdd#48]
**Is your feature request related to a problem? Please describe.**
Currently `suite.AddStep` returns an error which I could check if I want to handle invalid step definitions. This is a bit counterintuitive, because I certainly don't want to check them one by one.

**Describe the solution you'd like**
Ideally, the framework should probably check all step functions at once when calling `suite.Run`. I would like to see all invalid functions.

If it already does, then I would remove the returned error from `suite.AddStep` to have a cleaner API.

**Describe alternatives you've considered**
Add a `suite.MustAddStep` that terminates the test (`*testing.T` is already available at this point), but I think it would be better to see all invalid step functions.

**Comment by bkielbasa** [comment]
good point! Another alternative I can suggest is just failing the test. That would make it even simpler.

**Comment by sagikazarmark** [comment]
> Another alternative I can suggest is just failing the test.

Ultimately, that's what I'm suggesting as well, but it's not obvious where to do that.

The test could fail when `AddStep` is called, but I argue that validation should happen at the very beginning of `Run` instead, in which case I would not validate the func when adding it (that's where validation is at the moment).

**Comment by bkielbasa** [comment]
What's the benefit of failing it in `Run`? IMO it would be better to fail in `AddStep` because even the stack trace will show in which step is the problem. WDYT?

**Comment by sagikazarmark** [comment]
Failing in `Run` would allow yoou to see all the invalid steps at once and not one by one.

IMHO it would be quite annoying to fix one, go back, run tests again just to see there is another invalid value.

But I also see the point in failing early.

What does godog do?

**Comment by bkielbasa** [comment]
they panic very early https://github.com/DATA-DOG/godog/blob/master/suite.go#L101

**Comment by sagikazarmark** [comment]
Well, that's not that good. :)

But failing early it is then.

**Comment by bkielbasa** [comment]
what about validating them early and creating an array of errors which will be displayed when the user call `Run()`? If there's no error, the execution will be as it's now.

**Comment by sagikazarmark** [comment]
That's exactly my original proposal. Sounds good to me.
