### ISSUE TITLE
Use functional options

### ISSUE THREAD

**Issue by sagikazarmark** [go-bdd/gobdd#49]
**Is your feature request related to a problem? Please describe.**
I'm all for clean APIs. No unnecessary information means I can focus on what's important.

Take the following:

```go
options := gobdd.NewSuiteOptions()

// probably add some options here...or not

suite := gobdd.NewSuite(t, options)
```

Even if I don't want to set any options, I need to initialize options.

**Describe the solution you'd like**

Functional options allow the following usage patterns:

```go
// I don't want to set any options, just gimme suite
suite := gobdd.NewSuite(t)

// I want to set some options, let me do that inline
suite := gobdd.NewSuite(t, gobdd.WithBeforeSuite(func() {}))
```

**Describe alternatives you've considered**
Accept nil as the second parameter and initialize options if necessary (but that's still explicit)

**Additional context**
I can see options is implemented as a fluent interface, but functional options make cleaner APIs and more readable code.

**Comment by bkielbasa** [comment]
I was thinking about it as well but my idea was something like the below:

```go
suite := gobdd.NewSuite(t).WithAnOption(123)
```
or alternatively...

```go
func NewSuite(t *testing.T, options ...SuiteOption) *Suite

// in your code
suite := gobdd.NewSuite(t, gobdd.WithOption(123), gobdd.WithOption(321))
```

WDYT?

**Comment by sagikazarmark** [comment]
Well, it depends.

`AddStep` (and to be honest, `Before/AfterScenario` as well) kinda belong to the suite for me. So `suite.AddStep` and `step.BeforeScenario` look like a nice interface.

The second example is exactly what I'm suggesting for the rest of the options. 🙂

**Comment by arberiii** [comment]
Can you please check my solution for this issue on this [pull request](https://github.com/go-bdd/gobdd/pull/70).
