### ISSUE TITLE
Improve debuging

### ISSUE THREAD

**Issue by bkielbasa** [go-bdd/gobdd#63]
**Describe the bug**
When tests fail, in the console we can find error logs which don't point the line where the actual problem is but where the panic (in most cases) was caught.

![image](https://user-images.githubusercontent.com/1235620/73723207-cce44f80-4728-11ea-9d5b-74a53fa7fded.png)

**To Reproduce**

All you need to do is to change something in a test to fail it.

![image](https://user-images.githubusercontent.com/1235620/73723310-04eb9280-4729-11ea-839c-349d79d1d043.png)

**Comment by bkielbasa** [comment]
do you have any idea how to fix it? We cannot go with a stable version with an issue like that :)

**Comment by sagikazarmark** [comment]
Well, for one I'm not sure every step must actually be a subtest.

**Comment by bkielbasa** [comment]
I did that to improve readability while watching the output of the test execution.

**Comment by arberiii** [comment]
@bkielbasa to catch when the actual error happens we may have to use the runtime package. Here is how we can implement it
```go

type Err struct {
	err  string
	line int
	file string
}

func NewErr(s string) Err {
	stack := make([]uintptr, 1)
	_ = runtime.Callers(2, stack[:])
	file, line := runtime.FuncForPC(stack[0]).FileLine(stack[0] - 1)
	return Err{err: errors.New(s), file: file, line: line}
}

func (e Err) Error() string {
	return e.err
}
...

    return ctx, NewErr("the math does not work for you")
```

Then whenever we read error, we can also get in which file and which line it was called.
What do you think?

**Comment by bkielbasa** [comment]
Here's my proposal for the fix: https://github.com/go-bdd/gobdd/issues/73
Any other ideas?

**Comment by bkielbasa** [comment]
PRs are merged so I'm closing it :)
