### ISSUE TITLE
Proposal: remove panics from context.Get* methods and return errors explicitly

### ISSUE THREAD

**Issue by bkielbasa** [go-bdd/gobdd#77]
This proposal is connected to https://github.com/go-bdd/gobdd/issues/73.

The goal of the proposal is to remove all panics from the context helper methods and return errors explicitly. That will change the signature of those methods

```go
// from
func (ctx Context) GetString(key interface{}, defaultValue ...string) string {

// to
func (ctx Context) GetString(key interface{}, defaultValue ...string) (string, error) {
```

Here's an example implementation:

```go
func (ctx Context) GetString(key interface{}, defaultValue ...string) (string, error) {
	if len(defaultValue) > 1 {
       return"", fmt.Errorf("allowed to pass only 1 default value but %d got", len(defaultValue))
    }

	if _, ok := ctx.values[key]; !ok {
		if len(defaultValue) == 1 {
			return defaultValue[0]
		}
		return "", fmt.Errorf("the key %+v does not exist", key)
	}

	value, ok := ctx.values[key].(string)
	if !ok {
		return "", fmt.Errorf("the expected value is not string (%T)", key)
	}
	return value
} 
```

and in a test step

```go
stringVal, err := ctx.GetString("what-i-want")
if err != nil {
    t.Fatal(err)
}
```

This code would follow "handle errors explicitly" and general Go conventions but will add some boilerplate to the end user's code. Tradeoffs :)

**Comment by arberiii** [comment]
It look great to me, it would definitely help with debugging and its not that much to the end user's code as you said is Go convention so users are used to it.

**Comment by bkielbasa** [comment]
Do you have any arguments against the change? If now, I think I'll go for it.
