### ISSUE TITLE
[proposal] Move testhttp to a different repository

### ISSUE THREAD

**Issue by bkielbasa** [go-bdd/gobdd#90]
I've been thinking about releasing the stable version and realised that the biggest concern is the package `testhttp`. I'm not fully happy with its API. So I can suggest to remove it from the main repository and create a new one under `go-bdd` namespace.

**Comment by mirogta** [comment]
I like the idea. Would it also mean testhttp can evolve in its own pace?

**Comment by sagikazarmark** [comment]
I don't think I will ever use that package, so 👍 from me.

**Comment by bkielbasa** [comment]
@mirogta yes, it will have its own place. so, we have the decision  :)
