### ISSUE TITLE
Merge context package with the main package

### ISSUE THREAD

**Issue by sagikazarmark** [go-bdd/gobdd#96]
**Is your feature request related to a problem? Please describe.**
Currently the stdlib context and gobdd context packages can only be used in one file together with import aliases.

**Describe the solution you'd like**
Merge the context package with the main package. The functionality belongs closely together anyway.

**Describe alternatives you've considered**
Create an interface in the main package (interfaces belong to consumers).

Related #83

**Additional context**
This could be a backwards compatible change: we could keep the original package and add a type alias pointing to the new type in the root package.

**Comment by bkielbasa** [comment]
the context was moved to his own package because I had problems with `testhttp` package. Go doesn't permit import cycles. We removed the `testhttp` package from the main repository so IMO we can go for it.
